### ISSUE TITLE
establish data repository for brain data files

### ISSUE THREAD

**Issue by tperkis** [datastethoscope/code#12]
we must decide on and implement a mechanism for making data files as generated by gagan's lab for use by the development team, available to processes for download.

**Comment by VVander** [comment]
FTP server recommended for this, though any service with URL access should work.

**Comment by gswig** [comment]
Mike can you help neil and mic set this up for us locally?
--
Gagan S Wig, PhD

University of Texas at Dallas
Assistant Professor, School of Behavioral and Brain Sciences

University of Texas Southwestern Medical Center
Adjunct Assistant Professor, Department of Psychiatry

Center for Vital Longevity
1600 Viceroy Drive, Suite 800
Dallas, TX 75235

Ph:  972 883 3731
Web: http://vitallongevity.utdallas.edu/cnl/

**Comment by VVander** [comment]
Just sent Neil an email.

**Comment by VVander** [comment]
If we don't set this up before the end of the week, we won't get multiple time points available in the prototype phase as planned. An alternative is to just email the files to me for now and then get them hosted later. 

Would be better to get access to this data sooner rather than later.

**Comment by gswig** [comment]
Do we have a solution that gets around the UTD fire-wall? We cannot host locally for that reason.
--
Gagan S Wig, PhD

University of Texas at Dallas
Assistant Professor, School of Behavioral and Brain Sciences

University of Texas Southwestern Medical Center
Adjunct Assistant Professor, Department of Psychiatry

Center for Vital Longevity
1600 Viceroy Drive, Suite 800
Dallas, TX 75235

Ph:  972 883 3731
Web: http://vitallongevity.utdallas.edu/cnl/
