### ISSUE TITLE
StethoVis: Spatial Rendering Representation Plugin - basic functionality

### ISSUE THREAD

**Issue by VVander** [datastethoscope/code#5]
For the prototype phase, need to create the basic functions of a spatial rendering plugin to render data spatially according to coords in data. 

Nodes: cubes
Edges: debug lines (alpha of color = weight)

**Comment by VVander** [comment]
This will only be able to get so far before we need to use real data. For now I am working on rendering Node objects w/o real data attached.

**Comment by VVander** [comment]
Tests show almost instantaneous (~0.03 secs) instantiation & rendering of 441 randomly placed objects. Even when each of those objects have particle systems attached, rendering performance remains good on my machine (~65 fps).

**Comment by VVander** [comment]
Need real data to continue rendering development

**Comment by gswig** [comment]
Ive provided it in an email earlier today, good to go?
--
Gagan S Wig, PhD

University of Texas at Dallas
Assistant Professor, School of Behavioral and Brain Sciences

University of Texas Southwestern Medical Center
Adjunct Assistant Professor, Department of Psychiatry

Center for Vital Longevity
1600 Viceroy Drive, Suite 800
Dallas, TX 75235

Ph:  972 883 3731
Web: http://vitallongevity.utdallas.edu/cnl/

**Comment by VVander** [comment]
@gswig I meant the real data needs to be parsed into the program first. Sorry for the confusion.

**Comment by VVander** [comment]
Most of the work is completed. Still need to be able to draw edges. Plugin will continue development as required by other features (edge thresholding, etc) but work will be documented in those issues as they arise.
